sudo: true
language: python
python:
 - "3.4"
addons:
  postgresql: "9.4"

before_install:
  - export DJANGO_SETTINGS_MODULE=browserperfdash.settings
  - export PYTHONPATH=$HOME/builds/Igalia/browserperfdash

install:
  - pip install -r requirements.txt
  - npm install -g phantomjs-prebuilt

before_script:
  - psql -c "create role travisci with createrole createdb login password 'traviscipass';" -U postgres
  - psql -c "CREATE DATABASE traviscidb;" -U postgres

script:
  - python manage.py collectstatic --noinput
  - python manage.py makemigrations
  - python manage.py migrate --noinput --traceback --settings=browserperfdash.settings
  - python manage.py test

branches:
 only:
  - master

