# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpuarchitecture',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
