# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_cpuarchitecture_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPUType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='GPU Type Name')),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Platform Name')),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
