# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Browser',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Browser Id')),
                ('name', models.CharField(max_length=50, verbose_name='Browser Name')),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MetricUnit',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Metric Name')),
                ('unit', models.CharField(blank=True, max_length=10, verbose_name='Metric Unit')),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='Metric Description')),
                ('prefix', models.CharField(blank=True, max_length=50, verbose_name='Metric Prefix')),
                ('is_better', models.CharField(choices=[('dw', 'Down'), ('up', 'Up')], default='dw', max_length=2, verbose_name='Is Better')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Test Id')),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='Test Description')),
                ('url', models.CharField(blank=True, max_length=150, verbose_name='Test URL')),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
